# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hvN44_54oBiZxX-3yIkGhpEwiyELNbak
"""

import pandas as pd
import numpy as np
print("Hello Capstone Project Course!")

